- hosts: all
  become: yes
  become_method: sudo
  tasks:
    - name: install oracale java 8
      import_tasks: java8.yml

    - name: install druid
      import_tasks: druid.yml

    - name: install superset
      import_tasks: superset.yml

    - name: install supervisor and restart services
      import_tasks: supervisor.yml

